name: Lior Ben-Yehoshua
markdown: redcarpet
pygments: true
github: https://www.github.com/lior9999
about: I'm Lior!
urls:
    - text: github
      url: https://github.com/lior9999
    - text: email
      url: admin@lior9999.me
